### ISSUE TITLE
Doc needed about theming colors

### ISSUE THREAD

**Issue by GioviQ** [keycloakify/keycloakify-starter#29]
Inspecting html I discovered that Patternfly is used.

Please can you provide some hints in docs to change colors globally in keycloakify-starter?

https://www.patternfly.org/design-foundations/colors

**Comment by GioviQ** [comment]
I see now the Patternfly is quoted in Account Theme only in https://docs.keycloakify.dev/account-theme/single-page

**Comment by garronej** [comment]
Hello @GioviQ,

Yes, PatternFly is the CSS framework used by RedHat for building all their UIs, and since Keycloak is a RedHat product, it naturally uses PatternFly as well.

However, most developers customizing Keycloak themes prefer to use other, more widely adopted solutions instead of relying on PatternFly. That being said, overriding PatternFly's colors is still a good approach, and there isn’t anything specific to Keycloakify that would complicate this. You can simply refer to the official PatternFly documentation for guidance.

For example, to change the theme colors, you can do something like this:

<img width="1535" alt="code example" src="https://github.com/user-attachments/assets/3e9ebe07-8af5-42b7-af99-e9340fc0b1ed">  

<img width="975" alt="image" src="https://github.com/user-attachments/assets/076b5352-5e95-4b05-9cdc-1c4240b25d86">


And here’s what the result will look like:

<img width="2056" alt="theme result" src="https://github.com/user-attachments/assets/5f2620c5-7790-4054-878f-ca36fb7bd5b8">

**Comment by GioviQ** [comment]
I don't know why but in my case overriding css variables does not work.

**Comment by garronej** [comment]
My two first screenshot are from the starter repo, all I did was adding the main.css file and import it.

**Comment by GioviQ** [comment]
I am aging, I don't see well anymore, there was a "-" missing in variables names. Sorry.

**Comment by garronej** [comment]
Haha not problem!  

You should give ChatGPT a try, this is how I got the answer:  

<img width="1805" alt="image" src="https://github.com/user-attachments/assets/ca22291a-8c73-455a-ad39-b5410a4c0708">

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/908ceafd-7a3a-43c9-a000-77169ffdca97">

**Comment by GioviQ** [comment]
Thanks
Next step trying to understand how to add missing italian translations to Account UI Single-page... 😫
